#!/bin/zsh
### Program alias ###
alias -s pdf=pdf
alias -s {avi,mpeg,mpg,mov,wmv}=mplayer
alias -s {odt,doc,rtf}=oowriter
alias -s {jpg,png,svg,xpm,bmp,gif}=gpicview

### Global Alias ###
alias -g KEY='/etc/portage/package.keywords'
alias -g USE='/etc/portage/package.use'
alias -g NEW='/home/aparicio/Downloads/**/*(.oc[1])'
alias -g NEW2='/home/aparicio/Downloads/**/*(.oc[2])'
alias -g NEW3='/home/aparicio/Downloads/**/*(.oc[3])'
alias -g WWW='/var/www/localhost/htdocs/'
alias -g AUTO='--autounmask-write'
alias -g V='| vim -'

### Replaces ###
alias ls="ls --color=auto --group-directories-first"
alias grep='grep --colour=auto'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias wcalc='noglob wcalc --ints -EE'
alias emerge='noglob emerge'
alias ip="ip -c"

### Shortcuts ###
alias l="ls"
alias la="ls -a"
alias ll="ls -lhG"
alias al="ls -lhGa"
alias rf='rm -rf'
alias cls='cd && echo -n "]0;${USER}@${HOST}" && clear'
alias nuke='pkill -9'
alias untar="tar xvf"
alias clean="make clean"
alias remake="make clean && make"
alias ff="find . -type f -name"
alias psu="ps -Hc -F S f -u $USER"
alias psall="ps -ejH"

### Scripts ###
alias {t,term}="/home/aparicio/scripts/uterm"

### VCS ###
#alias up="svn update"
#alias commit="svn commit"
#alias log="svn log"
#alias changelog="svn2cl --authors=AUTHORS"
alias pull="git pull"
alias push="git push"
alias commit="git commit -a"
alias log="git log"
alias status="git status"

### Gentoo ###
alias update="emerge -uDNav"
alias cur="genlop -c"
alias belongs="qfile"
alias depends="equery depends"

### Hardware  ###
alias writeiso="cdrecord -v -pad dev=/dev/cdrom"
alias blankcd="cdrecord dev=/dev/cdrom blank=fast"
alias bat="cat /sys/class/power_supply/BAT*/uevent"
alias min="xbacklight -set 0 && 1000"
alias max="xbacklight -set 100 && 2000"

### Other ###
alias http="python3 -m http.server 9999"
alias weather="curl http://wttr.in/"
alias record="script -t 2> demo.timing -a demo.session"
alias replay="scriptreplay demo.timing demo.session"
alias 010="setxkbmap pt"
alias zshrc="source ~/.zshrc"
alias tcp="lsof -i tcp"
alias rcp="rsync --archive --one-file-system --hard-links --human-readable --inplace --numeric-ids --delete --delete-excluded --progress --compress"
alias drop_caches="echo 3 > /proc/sys/vm/drop_caches"
alias distc-monitor="DISTCC_DIR="/var/tmp/portage/.distcc/" distccmon-text 1"
alias rdp="rdesktop -k pt -u virtual -p -"
alias stress="perl -e 'while (--$ARGV[0] and fork) {}; while () {}'"
alias iptables_open="iptables -A INPUT -p tcp -j ACCEPT --dport"
alias iptables_close="iptables -D INPUT -p tcp -j ACCEPT --dport"
alias listen="ss -lp | column"
alias pasta="xclip -i -selection clipboard"

### Functions ###

start()		{ /etc/init.d/$@ start }
stop()		{ /etc/init.d/$@ stop }
restart()	{ /etc/init.d/$@ restart }
pause()		{ /etc/init.d/$@ --nodeps stop }

usage()		{ du -skch $@ | sort -rh }
unix2date()	{ date -ud@$@}
date2unix()	{ date +%s --date="$@"}
wiki()		{ dig +short txt $1.wp.dg.cx }
avg()		{ echo "($@)/$#" | tr ' ' '+' | wcalc }
cl()		{ cd $@; ls }

base()		{ echo "obase=$2; ibase=$1; $3" | bc }
alias dec2bin="base 10 2"
alias bin2dec="base 2 10"
alias dec2hex="base 10 16"
alias hex2dec="base 16 10"

pdf() {
	local i
	for i in $@; do
		if [ -e $i ]; then
			zathura $i 2>/dev/null&
		else
			echo "File '$i' does not exist"
		fi
	done
}

..() {
	local i j
	for ((j=${1:-1},i=0;i<j;i++));do
		builtin cd ..;
	done;
}
alias ..2=".. 2"
alias ..3=".. 3"
alias ..4=".. 4"
alias ..5=".. 5"
alias ...=".. 2"
alias ....=".. 3"

youtube-mp3() {
	local url=$1
	local file=$(youtube-dl -s -e $url);
	echo "Downloading $file"
	wget -q -O - `youtube-dl -b -g $url`| ffmpeg -i - -f mp3 -vn -acodec libmp3lame - > "$file.mp3"
}

warn() {
	$@
	notify-send-wrapper -t 0 "##### Command Done #####"  "\n$*\n"
}
alias -g W="warn"
